/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.ecommerce.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Notification service. Represents a row in the &quot;rivetlogic_ecommerce_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.ecommerce.model.impl.NotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.ecommerce.model.impl.NotificationImpl}.
 * </p>
 *
 * @author rivetlogic
 * @see Notification
 * @see com.rivetlogic.ecommerce.model.impl.NotificationImpl
 * @see com.rivetlogic.ecommerce.model.impl.NotificationModelImpl
 * @generated
 */
@ProviderType
public interface NotificationModel extends BaseModel<Notification>, ShardedModel,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification model instance should use the {@link Notification} interface instead.
	 */

	/**
	 * Returns the primary key of this notification.
	 *
	 * @return the primary key of this notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification.
	 *
	 * @param primaryKey the primary key of this notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this notification.
	 *
	 * @return the uuid of this notification
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this notification.
	 *
	 * @param uuid the uuid of this notification
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the notification ID of this notification.
	 *
	 * @return the notification ID of this notification
	 */
	public long getNotificationId();

	/**
	 * Sets the notification ID of this notification.
	 *
	 * @param notificationId the notification ID of this notification
	 */
	public void setNotificationId(long notificationId);

	/**
	 * Returns the group ID of this notification.
	 *
	 * @return the group ID of this notification
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this notification.
	 *
	 * @param groupId the group ID of this notification
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this notification.
	 *
	 * @return the company ID of this notification
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this notification.
	 *
	 * @param companyId the company ID of this notification
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this notification.
	 *
	 * @return the user ID of this notification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this notification.
	 *
	 * @param userId the user ID of this notification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notification.
	 *
	 * @return the user uuid of this notification
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notification.
	 *
	 * @param userUuid the user uuid of this notification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this notification.
	 *
	 * @return the create date of this notification
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this notification.
	 *
	 * @param createDate the create date of this notification
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this notification.
	 *
	 * @return the modified date of this notification
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this notification.
	 *
	 * @param modifiedDate the modified date of this notification
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the order ID of this notification.
	 *
	 * @return the order ID of this notification
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this notification.
	 *
	 * @param orderId the order ID of this notification
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the subject of this notification.
	 *
	 * @return the subject of this notification
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this notification.
	 *
	 * @param subject the subject of this notification
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this notification.
	 *
	 * @return the body of this notification
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this notification.
	 *
	 * @param body the body of this notification
	 */
	public void setBody(String body);

	/**
	 * Returns the sender of this notification.
	 *
	 * @return the sender of this notification
	 */
	@AutoEscape
	public String getSender();

	/**
	 * Sets the sender of this notification.
	 *
	 * @param sender the sender of this notification
	 */
	public void setSender(String sender);

	/**
	 * Returns the recipients of this notification.
	 *
	 * @return the recipients of this notification
	 */
	@AutoEscape
	public String getRecipients();

	/**
	 * Sets the recipients of this notification.
	 *
	 * @param recipients the recipients of this notification
	 */
	public void setRecipients(String recipients);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Notification notification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Notification> toCacheModel();

	@Override
	public Notification toEscapedModel();

	@Override
	public Notification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}