/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.ecommerce.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ShoppingOrderItem service. Represents a row in the &quot;rivetlogic_ecommerce_ShoppingOrderItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemImpl}.
 * </p>
 *
 * @author rivetlogic
 * @see ShoppingOrderItem
 * @see com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemImpl
 * @see com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemModelImpl
 * @generated
 */
@ProviderType
public interface ShoppingOrderItemModel extends BaseModel<ShoppingOrderItem>,
	ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Shopping Order Item model instance should use the {@link ShoppingOrderItem} interface instead.
	 */

	/**
	 * Returns the primary key of this Shopping Order Item.
	 *
	 * @return the primary key of this Shopping Order Item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Shopping Order Item.
	 *
	 * @param primaryKey the primary key of this Shopping Order Item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this Shopping Order Item.
	 *
	 * @return the uuid of this Shopping Order Item
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this Shopping Order Item.
	 *
	 * @param uuid the uuid of this Shopping Order Item
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the item ID of this Shopping Order Item.
	 *
	 * @return the item ID of this Shopping Order Item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this Shopping Order Item.
	 *
	 * @param itemId the item ID of this Shopping Order Item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the group ID of this Shopping Order Item.
	 *
	 * @return the group ID of this Shopping Order Item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Shopping Order Item.
	 *
	 * @param groupId the group ID of this Shopping Order Item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Shopping Order Item.
	 *
	 * @return the company ID of this Shopping Order Item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Shopping Order Item.
	 *
	 * @param companyId the company ID of this Shopping Order Item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Shopping Order Item.
	 *
	 * @return the user ID of this Shopping Order Item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Shopping Order Item.
	 *
	 * @param userId the user ID of this Shopping Order Item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Shopping Order Item.
	 *
	 * @return the user uuid of this Shopping Order Item
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this Shopping Order Item.
	 *
	 * @param userUuid the user uuid of this Shopping Order Item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this Shopping Order Item.
	 *
	 * @return the create date of this Shopping Order Item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this Shopping Order Item.
	 *
	 * @param createDate the create date of this Shopping Order Item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Shopping Order Item.
	 *
	 * @return the modified date of this Shopping Order Item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Shopping Order Item.
	 *
	 * @param modifiedDate the modified date of this Shopping Order Item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the order ID of this Shopping Order Item.
	 *
	 * @return the order ID of this Shopping Order Item
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this Shopping Order Item.
	 *
	 * @param orderId the order ID of this Shopping Order Item
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the product ID of this Shopping Order Item.
	 *
	 * @return the product ID of this Shopping Order Item
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this Shopping Order Item.
	 *
	 * @param productId the product ID of this Shopping Order Item
	 */
	public void setProductId(String productId);

	/**
	 * Returns the quantity of this Shopping Order Item.
	 *
	 * @return the quantity of this Shopping Order Item
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this Shopping Order Item.
	 *
	 * @param quantity the quantity of this Shopping Order Item
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the price of this Shopping Order Item.
	 *
	 * @return the price of this Shopping Order Item
	 */
	public double getPrice();

	/**
	 * Sets the price of this Shopping Order Item.
	 *
	 * @param price the price of this Shopping Order Item
	 */
	public void setPrice(double price);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ShoppingOrderItem shoppingOrderItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ShoppingOrderItem> toCacheModel();

	@Override
	public ShoppingOrderItem toEscapedModel();

	@Override
	public ShoppingOrderItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}